{{- if .Values.secrets.awsSecretEnabled -}}
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ include "mongo.fullname" . }}
spec:
  backendType: secretsManager
  dataFrom:
    - {{ .Values.secrets.awsSecret }}
{{- end }}