# Local testmongodb container
version: '3.1'

services:

  mongo:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=P@55w0rd
      - MONGO_INITDB_DATABASE=mongo_test
    volumes:
      - './mongodb:/data/db'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
